"""init

Revision ID: bce1e66bb101
Revises: 
Create Date: 2023-12-14 10:47:06.594959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bce1e66bb101"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password", sa.String(length=72), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index("users__id_idx", "users", ["id"], unique=False, postgresql_using="hash")
    op.create_index("users__username_idx", "users", ["username"], unique=False,
                    postgresql_using="hash")
    op.create_table(
        "senses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("data", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("senses__created_at_idx", "senses", ["created_at"], unique=False,
                    postgresql_using="btree")
    op.create_index("senses__id_idx", "senses", ["id"], unique=False, postgresql_using="hash")
    op.create_index("senses__user_id_idx", "senses", ["user_id"], unique=False,
                    postgresql_using="btree")
    op.create_table(
        "sessions",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index("sessions__token_idx", "sessions", ["token"], unique=False,
                    postgresql_using="hash")
    op.create_index("sessions__user_id_idx", "sessions", ["user_id"], unique=False,
                    postgresql_using="btree")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("sessions__user_id_idx", table_name="sessions", postgresql_using="btree")
    op.drop_index("sessions__token_idx", table_name="sessions", postgresql_using="hash")
    op.drop_table("sessions")
    op.drop_index("senses__user_id_idx", table_name="senses", postgresql_using="btree")
    op.drop_index("senses__id_idx", table_name="senses", postgresql_using="hash")
    op.drop_index("senses__created_at_idx", table_name="senses", postgresql_using="btree")
    op.drop_table("senses")
    op.drop_index("users__username_idx", table_name="users", postgresql_using="hash")
    op.drop_index("users__id_idx", table_name="users", postgresql_using="hash")
    op.drop_table("users")
    # ### end Alembic commands ###
