"""change indexes

Revision ID: ed569caafd85
Revises: bce1e66bb101
Create Date: 2023-12-18 15:31:56.733172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed569caafd85"
down_revision: Union[str, None] = "bce1e66bb101"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("senses__created_at_idx", table_name="senses")
    op.drop_index("senses__user_id_idx", table_name="senses")
    op.drop_index("sessions__user_id_idx", table_name="sessions")
    op.create_index("senses__created_at__id_idx", "senses", ["created_at", "id"], unique=False,
                    postgresql_using="btree")
    op.create_index("senses__user_id_idx", "senses", ["user_id"], unique=False,
                    postgresql_using="hash")
    op.create_index("sessions__user_id_idx", "sessions", ["user_id"], unique=False,
                    postgresql_using="hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("senses__created_at__id_idx", table_name="senses", postgresql_using="btree")
    op.drop_index("senses__user_id_idx", table_name="senses")
    op.drop_index("sessions__user_id_idx", table_name="sessions")
    op.create_index("senses__created_at_idx", "senses", ["created_at"], unique=False)
    op.create_index("senses__user_id_idx", "senses", ["user_id"], unique=False,
                    postgresql_using="btree")
    op.create_index("sessions__user_id_idx", "sessions", ["user_id"], unique=False,
                    postgresql_using="btree")
    # ### end Alembic commands ###
